# Generated by Django 3.2.8 on 2021-12-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd', '0003_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='letterboxd.Genre'),
        ),
    ]
