# Generated by Django 3.2.8 on 2021-12-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='film',
            field=models.ManyToManyField(to='letterboxd.Film'),
        ),
    ]
