# Generated by Django 3.2.8 on 2021-12-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd', '0006_review_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='film',
        ),
        migrations.AddField(
            model_name='review',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='letterboxd.film'),
        ),
    ]
