# Generated by Django 3.2.8 on 2021-12-07 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd', '0009_auto_20211205_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('film_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filmadded', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addingfilm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adding Films',
            },
        ),
    ]
