# Generated by Django 3.2.8 on 2021-12-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd', '0012_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='following',
            new_name='the_followed',
        ),
    ]
