# Generated by Django 3.2.8 on 2021-12-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd', '0013_rename_following_following_the_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='the_followed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
