# Generated by Django 3.2.8 on 2021-12-09 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd', '0016_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='films',
        ),
        migrations.AddField(
            model_name='like',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='letterboxd.film'),
        ),
    ]
